version: '3.8'

services:
  # Local development services only
  # MySQL and Redis are using cloud services
  # Uncomment below for local development with local services
  
  # mysql:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: warden_db
  #     MYSQL_USER: candidate_user
  #     MYSQL_PASSWORD: StrongPassword!123
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  # redis:
  #   image: redis/redis-stack:latest
  #   ports:
  #     - "6379:6379"
  #     - "8001:8001"
  #   volumes:
  #     - redis_data:/data

  # Backend API
  backend:
    build:
      context: ./backend
      target: production
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      PORT: 5002
    ports:
      - "5002:5002"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5002
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  # Monitoring
  monitoring:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'

# volumes:
  # mysql_data:
  # redis_data:

networks:
  default:
    name: warden-network